// Helpers for parsing inline ingredient tags from step instructions.
// Step descriptions contain inline tags generated by Gemini: `[word in text](ing:baseName)`.
// E.g., "Die [Eigelbe](ing:Ei) und das [Ei](ing:Ei) mit dem [Parmesan](ing:Parmesan) verrühren."

const INLINE_TAG_REGEX = /\[([^\]]+)\]\(ing:([^)]+)\)/g;

export interface InlineIngredientMatch {
  wordInText: string;
  baseName: string;
}

/**
 * Extracts all inline ingredient tags `[word](ing:baseName)` present in a step description.
 */
export function extractInlineIngredientTags(text: string): InlineIngredientMatch[] {
  if (!text) return [];
  const matches: InlineIngredientMatch[] = [];
  const regex = new RegExp(INLINE_TAG_REGEX);
  let match: RegExpExecArray | null;

  while ((match = regex.exec(text)) !== null) {
    matches.push({
      wordInText: match[1],
      baseName: match[2].trim(),
    });
  }

  return matches;
}

/**
 * Strips all inline `[word](ing:baseName)` tags from a text string, returning plain text `word`.
 */
export function stripInlineIngredientTags(text: string): string {
  if (!text) return '';
  return text.replace(INLINE_TAG_REGEX, '$1');
}

/**
 * Language-neutral fallback for legacy recipes without inline tags:
 * Checks whether `text` mentions `term` as a standalone word.
 */
export function textMentionsTerm(term: string | undefined | null, text: string): boolean {
  if (!term || !text) return false;
  const trimmed = term.trim();
  if (trimmed.length < 2) return false;

  const escaped = trimmed.replace(/[-/\\^$*+?.()|[\]{}]/g, '\\$&');
  const boundary = `[\\s.,:;!?()\\[\\]{}'"\\-\\/]`;

  try {
    const regex = new RegExp(`(?<=^|${boundary})${escaped}(?=$|${boundary})`, 'iu');
    return regex.test(text);
  } catch {
    return text.toLowerCase().includes(trimmed.toLowerCase());
  }
}
